name: Run SQLite Task
on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  sqlite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Add mask for secrets
        run: |
          echo '${{ secrets.ENV_SECRETS }}' | jq -r 'to_entries | .[] | .value' | while read -r value; do
            echo "::add-mask::$value"
          done          
      - name: Set environment variables
        run: |
          echo '${{ secrets.ENV_SECRETS }}' | jq -r 'to_entries | .[] | "echo \(.key)=\(.value) >> $GITHUB_ENV"' | sh

      - name: Install dependencies
        run: npm install
        
      - name: Run index.js
        run: npm run dev
        env:
          RUN_ONCE: true

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./data/db.sqlite
          git add ./json/
          git commit -m "Update from collection"
          git push
